pipeline{
    agent {
        node {
            label 'AGENT-1'
        }
    }
    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    environment{
        GREETING = "Hello Jenkins"
    }
    
    stages{
        stage("Init") {
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure 
                """    
            }
        }
        stage("Plan") {
            steps {
                sh """
                    cd 01-vpc
                    terraform plan 
                """   
            }
        }
        stage('Deploy'){
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                ""'  
            }
        }
        
    }
    post {
        always {
            echo 'I will always say Hello again!'
        }
        success {
            echo "pipeline is success"
        }
        failure {
            echo "pipeline is failed"
        }    
    }

} 
